import { getServerSession } from "next-auth";
import "./globals.css";
import { NextAuthProvider } from "./providers";
import { authOptions } from "../lib/auth";

export const metadata = {
  title: "Tic Tac Toe",
  description: "Generated by create next app",
};

export async function createOrUpdateUser() {
  const session = await getServerSession(authOptions);
  const user = session?.user;

  if (!user) return;

  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/users`, {
    method: "POST",
    body: JSON.stringify({
      name: user?.name,
      email: user?.email,
      image: user?.image,
    }),
  });
  if (!res.ok) {
    console.error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  if (!process.env.NEXT_PUBLIC_API_URL) {
    return null;
  }
  await createOrUpdateUser();
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
